# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ammar Najjar's Personal Blog
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://ammarnajjar.github.io" # the base hostname & protocol for your site
twitter_username: ammarnajjar
github_username:  ammarnajjar
linkedin_username:  najjarammar
xing_username:  Ammar_Najjar

# Build settings
markdown: kramdown
highlighter: rouge
